### ISSUE TITLE
Right icon never leaves

### ISSUE THREAD

**Issue by carvalho2707** [xabaras/RecyclerViewSwipeDecorator#1]
Hey, 
I was just trying your library and i came up with a bug.
If i swap one time, the right icon appears(that's ok) but then it never leaves :/

![image](https://user-images.githubusercontent.com/3799625/40919056-3c491752-6800-11e8-8c02-02d77bb021a3.png)

![image](https://user-images.githubusercontent.com/3799625/40919080-51fbaf24-6800-11e8-91ba-3280ea92a093.png)

**Comment by xabaras** [comment]
What do you mean with "it never leaves"?
Can you provide more detailed information?

**Comment by carvalho2707** [comment]
Sorry, I've accidentally submit the issue without finishing it

**Comment by xabaras** [comment]
Ok, thanks, I'll have a look and let you know

**Comment by xabaras** [comment]
Ok, can you tell me against wich version of the ReciclerView library are you building  your app?

**Comment by carvalho2707** [comment]
com.android.support:recyclerview-v7:27.1.1

**Comment by xabaras** [comment]
Last commit (#234be3a) fixes the issue.
A new version of the library will be available on maven central and JCenter as soon as possible.
Thanks for reporting the issue!

**Comment by carvalho2707** [comment]
Hey, Just to let you know that I've tested the latest version in my app and it did fix the issue.
Thanks for you work and keep it up ;)

**Comment by xabaras** [comment]
Sorry, can you tell me the steps to reproduce the issue?
It doesn't seem to happen with version 1.0.1  of the library in the sample app.
Do you dismiss the row after swiping?

**Comment by xabaras** [comment]
Good!
Than you for submitting the issue and allowing me to improve my code.
