### ISSUE TITLE
swipe background don't disappear after on swiped called.

### ISSUE THREAD

**Issue by MrAndroi** [xabaras/RecyclerViewSwipeDecorator#11]
swipe background don't disappear after on swiped called.... when i finish the swiping i want the background to go how i can do this?

**Comment by meafs** [comment]
@MrAndroi in your `onSwiped` method use this:

```
int position = viewHolder.getAdapterPosition();

if(direction == ItemTouchHelper.LEFT)
    {
        adapter.notifyItemChanged(position);  // Add this line

      }

```

Your background will be back.

**Comment by xabaras** [comment]
@meafs thanks for answering
