### ISSUE TITLE
SwipeDecorator not compatible with androidx recyclerview and viewHolder

### ISSUE THREAD

**Issue by AkkiBuoy** [xabaras/RecyclerViewSwipeDecorator#14]
The SwipeDecorator.Builder() method takes Recyclerview and ViewHolder as arguments but they are not compatible with android x versions.

**Comment by xabaras** [comment]
Sorry, I've not yet ported it to androidx. Hope to be doing this soon.

Il mar 18 mag 2021, 07:36 AkkiBuoy ***@***.***> ha scritto:

**Comment by carv3l** [comment]
@AkkiBuoy 

The Problem is when you swipe and the background Color and icon , stays?

**Comment by xabaras** [comment]
Version 1.3 (#17) solves the issue.
