### ISSUE TITLE
androidX compatibility ??

### ISSUE THREAD

**Issue by khaledmamartech** [xabaras/RecyclerViewSwipeDecorator#15]
The SwipeDecorator.Builder() method takes Recyclerview and ViewHolder as arguments but they are not compatible with android x versions.
Any idea to do???

**Comment by xabaras** [comment]
Just working on it, hope to release a new version soon

**Comment by Albedici** [comment]
For me replacing
import android.support.v4.content.ContextCompat;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.helper.ItemTouchHelper;

with 
import androidx.core.content.ContextCompat;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.recyclerview.widget.RecyclerView;

worked fine

**Comment by LeeYH99** [comment]
> For me replacing
> import android.support.v4.content.ContextCompat;
> import android.support.v7.widget.RecyclerView;
> import android.support.v7.widget.helper.ItemTouchHelper;
> 
> with
> import androidx.core.content.ContextCompat;
> import androidx.recyclerview.widget.ItemTouchHelper;
> import androidx.recyclerview.widget.RecyclerView;
> 
> worked fine

Hi, may I know whr to change this? I tried in the TouchHelper class but it still doesn't work.

**Comment by Klewerro** [comment]
> Hi, may I know whr to change this? I tried in the TouchHelper class but it still doesn't work.

I've just copied and pasted library code in my project, and IDE made all imports automatically (and translate code to Kotlin in my case) in AndroidX based project ;)

**Comment by xabaras** [comment]
Thank you all for your contribution.
Version 1.3 (#17) solves the issue.
