### ISSUE TITLE
Could you provide Text, which is drawn next to the icon?

### ISSUE THREAD

**Issue by JST2018** [xabaras/RecyclerViewSwipeDecorator#2]
Hey thank, you for your little RecyclerViewDecorator.

Is it possible to provide Text, which is drawn next to the icon, for example delete next to trashbin?

Regards,
JST2018

**Comment by xabaras** [comment]
Thanks for the feature request!
I'm working on it and will release an update soon.

**Comment by xabaras** [comment]
@JST2018 did it solve your problem?

**Comment by JST2018** [comment]
Sorry for the delayed answer. In my project nothing happened until now. It looks promising, so I will try it.

**Comment by xabaras** [comment]
Ok, let me know if it closes the issue.

**Comment by JST2018** [comment]
Hi there,
looks nice but I can't get the label text color to white. And what is the argument unit in this method: setSwipeLeftLabelTextSize(int unit, float size)?

**Comment by xabaras** [comment]
The unit parameter is a TypedValue like in TextVIew.setTextSize, e.g. TypedValue.COMPLEX_UNIT_SP
The text color should be set correctly, have a look at the sample app, can you show me your code?
