### ISSUE TITLE
Security threat?

### ISSUE THREAD

**Issue by uestueab** [xabaras/RecyclerViewSwipeDecorator#20]
Hey, i'm getting a "security threat" notification on my huawei p40 saying: "<myapp> appears to be infected [...]". Do you have a clue why this appears on my screen? I only included it in my build.gradle file.

**Comment by xabaras** [comment]
Can you tell me more?
Which version of the library did you include in your project?

**Comment by xabaras** [comment]
The library version 1.4 is now available on Maven Central, this should solve your issue.
