### ISSUE TITLE
Depreciated

### ISSUE THREAD

**Issue by DAHarder** [xabaras/RecyclerViewSwipeDecorator#21]
After upgrading to the Androidx version, the method is showing as Depreciated.  I cannot tell if this is my issue, or yours.

I am relatively new to Android Programming, so I apologize if this is a silly issue.

![image](https://user-images.githubusercontent.com/55961828/132776298-d488f436-e492-4b8b-ab12-8efdff99decb.png)

**Comment by DIRRHUB** [comment]
I have the same problem

**Comment by xabaras** [comment]
Sure, It is correctly show as deprecated, you should use the constructor below, which doesn't take context as a parameter but uses the one from the RecyclerView itself:

`public Builder(Canvas canvas, RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder, float dX, float dY, int actionState, boolean isCurrentlyActive)`
