### ISSUE TITLE
Kotlin Problem with Upgrade Version RecyclerViewSwipeDecorator1.3 

### ISSUE THREAD

**Issue by fast050** [xabaras/RecyclerViewSwipeDecorator#22]
-hi , first of all thank you for make utility class this easier for us very very useful , am use it in my current code 

-I have notice it just stop working with this new upgrade I cant use this 

        RecyclerViewSwipeDecorator.Builder(c, recyclerView, viewHolder, dX, dY, actionState, isCurrentlyActive)
            .addBackgroundColor(ContextCompat.getColor(MainActivity.this, R.color.my_background))
            .addActionIcon(R.drawable.my_icon)
            .create()
            .decorate();

although it was working fine with the last version recyclerview-swipedecorator:1.2.3

**Comment by fastesol** [comment]
Did you find any solution?

**Comment by xabaras** [comment]
Sorry for the belated answer, what do you mean with "stopped working" and "I can't use this"?
Do you get any compilation error?

**Comment by Titu-beep** [comment]
Failed to resolve: com.github.xabaras:RecyclerViewSwipeDecorator:1.3

I am getting this

**Comment by xabaras** [comment]
> 

Since version 1.3 you need to use jitpack, try adding the jitpack repository to your root build.gradle, e.g.:

```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by Titu-beep** [comment]
Did that.... Not working .. I am using Java language

**Comment by xabaras** [comment]
Just tried on a Java project and it built and run.
You need to:
1) add this to you Project build.gradle
    maven { url 'https://jitpack.io' }
2) add the dependency to your module's (e.g. app) build.gradle
implementation 'com.github.xabaras:RecyclerViewSwipeDecorator:1.4'

Let me know if you succeed.

**Comment by xabaras** [comment]
The library version 1.4 is now available on Maven Central, this should solve your issue.
