### ISSUE TITLE
Can you add  Long left swipe and  Long right swipe

### ISSUE THREAD

**Issue by biniamHaddish** [xabaras/RecyclerViewSwipeDecorator#3]

**Comment by xabaras** [comment]
Can you explain what do you mean with "long swipe"?

**Comment by xabaras** [comment]
Sorry, can you explain?

**Comment by biniamHaddish** [comment]
Hello there I have already implemented the feature in my library https://github.com/biniamHaddish/SwipeView 
thanks for the reply.
