### ISSUE TITLE
On Grid Layout background color overlap

### ISSUE THREAD

**Issue by AndreKelvin** [xabaras/RecyclerViewSwipeDecorator#5]
First of i want to thank you for implementing this and making it easy to use.
So i'm working on a note app that convert from Linear Layout to Grid Layout and Grid Layout to Linear Layout when an icon is clicked.
On Grid, when swipe right the background color overlaps the other item view
![recyclerviewgridbug](https://user-images.githubusercontent.com/39889856/60774091-dc55d880-a106-11e9-8023-9f526e61d54c.gif)

**Comment by xabaras** [comment]
Thanks for reporting the issue! Will be fixed soon in the next release.

**Comment by xabaras** [comment]
It should be fixed in 1.2 library version.
Can you confirm?

**Comment by AndreKelvin** [comment]
Yes i have. this is more better then before. but as you can see the icon didn't display when swipe right
thanks anyway 
![bugFixed](https://user-images.githubusercontent.com/39889856/61066937-68654a00-a3fe-11e9-956a-de768a8bfd7f.gif)

**Comment by xabaras** [comment]
Just published version 1.2.1 which should fix your issues

**Comment by AndreKelvin** [comment]
Yes it did. Thanks your effort

**Comment by xabaras** [comment]
Thank you for using my lib and for taking the time to reporting issues.
If you notice something else that's not working properly, let me know.

Happy coding!
