### ISSUE TITLE
Why take `context` in `Builder(context...`

### ISSUE THREAD

**Issue by danielgindi** [xabaras/RecyclerViewSwipeDecorator#6]
You are already taking a `RecyclerView`, you can take `recyclerView.context`.
So the user does not have to reference outer classes to find a context :-)

**Comment by xabaras** [comment]
Thanks for the advice, I'll work on this in the next version of the lib.

**Comment by xabaras** [comment]
Just published version 1.2.2 wich deprecates constructors with context and switches to recyclerView.context
