### ISSUE TITLE
How to remove right swipe from drawing in particular recyclerview?

### ISSUE THREAD

**Issue by Dhruvi-Matrix** [xabaras/RecyclerViewSwipeDecorator#8]
I am having functionality to have right swipe for one item and left and right swipe for some item. so can u guide how to disable particular swipe direction?

**Comment by abhriyaroy** [comment]
Any update?

**Comment by xabaras** [comment]
This is now about RecyclerViewSwipeDecorator but about the RecyclerView itself.
BTW you should be able to manage this by overriding the getSwipeDirs method in the SimpleCallback object and return the proper value based on ViewHolder adapter position.
